Repository IamBisrutPyne/Java-Programs, pull requests merged in 2025-10, with the labels that each got.

#1 Create DisariumNumber.java
  DisariumNumber.java
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest-accepted2025

#2 Create volumeFunctionOverloading.java
  volumeFunctionOverloading.java
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest-accepted2025

#4 Create StudentLibraryManagementSystem.java
  StudentLibraryManagementSystem.java
Labels: enhancement, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest-accepted2025

#5 Add: Dijkstra Algo using Java
  Dijkstra.java
  StackDemo.java
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added CONTRIBUTING and CODE OF CONDUCT files.
  CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest-accepted2025

#11 Added java program for Bank Account Management(OOP)
  OOP/BankAccountManagement.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 Added Sieve of Eratosthenes Program
  Algorithms/SieveOfEratosthenes.java
Labels: hacktoberfest, hacktoberfest-accepted

#14 Reorganize
  Algorithms/Dijkstra.java
  Algorithms/Knapsack.java
  Beginner/DisariumNumber.java
  Beginner/NarcissisticNumber.java
  Beginner/volumeFunctionOverloading.java
  DataStructures/StackDemo.java
  OOP/StudentLibraryManagementSystem.java
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added KMP Algorithm In Java
  Algorithms/KMPAlgorithm.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#45 Bellman-ford algo added
  Algorithms/BellmanFord.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 feat: add Queue implementation using custom singly linked list
  DataStructures/Queue.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
